apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: cloudcart

spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  volumeName: mongodb-pv