apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: {{ .Values.namespace }}

  labels:
{{ include "cloudcart.labels" . | nindent 4 }}

spec:

  selector:

    app: frontend

  ports:

  - port: 80

    targetPort: 80

  type: ClusterIP