# -----------------------------
# Stage 1 - Build React App
# -----------------------------
FROM node:22-alpine AS builder

WORKDIR /app

ARG VITE_API_BASE_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


# -----------------------------
# Stage 2 - Nginx
# -----------------------------
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]