apiVersion: apps/v1

kind: Deployment

metadata:
  name: product-service
  namespace: cloudcart

  labels:
    app: product-service

spec:

  replicas: 2

  selector:
    matchLabels:
      app: product-service

  template:

    metadata:
      labels:
        app: product-service

    spec:

      containers:

        - name: product-service

          image: cloudcart-product-service:v1

          imagePullPolicy: Never

          ports:

            - containerPort: 8001

          envFrom:

            - configMapRef:
                name: product-service-config

            - secretRef:
                name: product-service-secret

          resources:

            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:

            httpGet:
              path: /health
              port: 8001

            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:

            httpGet:
              path: /health
              port: 8001

            initialDelaySeconds: 10
            periodSeconds: 5