apiVersion: v1

kind: Service

metadata:
  name: product-service
  namespace: cloudcart

spec:

  selector:
    app: product-service

  ports:

    - port: 8001
      targetPort: 8001

  type: ClusterIP