{{- range $name, $service := .Values.services }}

{{- if $service.enabled }}

apiVersion: v1
kind: Service

metadata:

  name: {{ $name }}

  namespace: {{ $.Values.namespace }}

spec:

  selector:

    app: {{ $name }}

  ports:

  - port: {{ $service.port }}

    targetPort: {{ $service.port }}

  type: ClusterIP

---

{{- end }}

{{- end }}