const NOTIFICATION_TYPE = {

    ORDER_CREATED: "ORDER_CREATED",

    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",

    PAYMENT_FAILED: "PAYMENT_FAILED",

    ORDER_CANCELLED: "ORDER_CANCELLED"

};

module.exports = NOTIFICATION_TYPE;