apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: {{ .Values.namespace }}

  labels:
{{ include "cloudcart.labels" . | nindent 4 }}

spec:

  accessModes:
    - ReadWriteOnce

  resources:

    requests:

      storage: {{ .Values.mongodb.storage }}