apiVersion: v1
kind: ConfigMap

metadata:
  name: api-gateway-config
  namespace: cloudcart

data:
  PORT: "5000"

  USER_SERVICE_URL: http://user-service:8000

  PRODUCT_SERVICE_URL: http://product-service:8001

  ORDER_SERVICE_URL: http://order-service:8002

  CART_SERVICE_URL: http://cart-service:8003

  PAYMENT_SERVICE_URL: http://payment-service:8004

  NOTIFICATION_SERVICE_URL: http://notification-service:8005

  CORS_ORIGIN: http://cloudcart.local