apiVersion: v1
kind: ConfigMap

metadata:
  name: cart-service-config
  namespace: cloudcart

data:

  PORT: "8003"

  MONGO_URI: mongodb://mongodb:27017/cloudcart_cart

  JWT_EXPIRES_IN: "1d"

  PRODUCT_SERVICE_URL: http://product-service:8001