apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-service-config
  namespace: cloudcart

data:

  PORT: "8005"

  MONGO_URI: mongodb://mongodb:27017/cloudcart_notification

  JWT_EXPIRES_IN: "1d"

  NOTIFICATION_PROCESSING_DELAY: "1000"

  NOTIFICATION_SUCCESS_RATE: "0.98"