apiVersion: v1
kind: ConfigMap

metadata:
  name: payment-service-config
  namespace: cloudcart

data:

  PORT: "8004"

  PAYMENT_PROCESSING_DELAY: "2000"

  PAYMENT_SUCCESS_RATE: "0.9"

  MONGO_URI: mongodb://mongodb:27017/cloudcart_payment

  JWT_EXPIRES_IN: "1d"