apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service
  namespace: cloudcart

  labels:
    app: payment-service

spec:

  replicas: 2

  strategy:

    type: RollingUpdate

    rollingUpdate:

      maxUnavailable: 1

      maxSurge: 1

  selector:

    matchLabels:

      app: payment-service

  template:

    metadata:

      labels:

        app: payment-service

    spec:

      containers:

        - name: payment-service

          image: cloudcart-payment-service:v1

          imagePullPolicy: Never

          ports:

            - containerPort: 8004

          envFrom:

            - configMapRef:
                name: payment-service-config

            - secretRef:
                name: cloudcart-secret

          resources:

            requests:

              cpu: "100m"

              memory: "128Mi"

            limits:

              cpu: "500m"

              memory: "512Mi"

          readinessProbe:

            httpGet:

              path: /health

              port: 8004

            initialDelaySeconds: 10

            periodSeconds: 5

          livenessProbe:

            httpGet:

              path: /health

              port: 8004

            initialDelaySeconds: 20

            periodSeconds: 10